#!/usr/bin/env bash

usage () { 
    echo "usage: <path-to-scripts>/${0##*/} [start]"; 
}

if [ -z "$1" ]
  then
    usage
    exit 1
fi

option=$1

case $option in
    start)
        current_id=$$
        ps -ef > file1.txt

        echo "$current_id"
        while [[ $current_id -ne 1 ]]
        do 
            current_id=$( cat file1.txt | awk '{if ( $2 == '$current_id' ) print $3;}')
            echo " |_ $current_id "
        done

        echo "";;
    *)
        usage;;
esac;
